name = "JuliaDG"
uuid = "e0202c1c-9d45-4c88-b6ab-2b34c932d0cf"
authors = ["JuliaDG contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
Makie = "ee78f7c6-7fb1-5441-9ec4-5a4bf5e1d5b2"

[extensions]
JuliaDGMakieExt = "Makie"

[compat]
Meshes = "0.57"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
